quarkus.datasource.db-kind=postgresql

%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.hibernate-orm.log.sql=false

%dev.quarkus.datasource.username=globex
%dev.quarkus.datasource.password=globex
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/globex

# OIDC  tenant that secures a protected REST server.
quarkus.oidc.auth-server-url=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:internal}
quarkus.oidc.client-id=${GLOBEX_STORE_APP_CLIENT_ID}
quarkus.oidc.agents-rest-server.auth-server-url=${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM:internal}
quarkus.oidc.agents-rest-server.token.audience=${GLOBEX_STORE_APP_AUDIENCE}
quarkus.oidc.agents-rest-server.tenant-paths=${GLOBEX_STORE_APP_TENANT_PATH}

quarkus.devservices.enabled=false

%dev.quarkus.http.port=8086

quarkus.http.cors.enabled=true
quarkus.http.cors.origins= *
quarkus.http.cors.methods=GET,POST,DELETE,OPTIONS
